AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
